application: lowcoupling
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: / 
  script: helloworld.py  
  
- url: /anotherpage\.html  
  script: helloworld.py
  
- url: /auth\.html 
  script: helloworld.py
 
- url: /mapPage\.html
  script: helloworld.py
  
  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest